-- generated on https://dbdiagram.io/d/5e568adaef8c251a06189cb3
-- PostgreSQL variant
create    table games (
          gms_id integer generated by default as identity primary key,
          gms_name varchar(255),
          gms_status varchar(255),
          gms_vote_style varchar(255),
          gms_created_at timestamp default current_timestamp,
          gms_revive integer
          );

create    table game_players (
          gpl_gms_id integer,
          gpl_slack_id varchar(255),
          gpl_name varchar(255),
          gpl_status varchar(255),
          gpl_leader boolean,
          gpl_drawn boolean,
          gpl_not_drawn boolean,
          gpl_number_of_messages integer,
          primary key (gpl_gms_id, gpl_slack_id),
          constraint fk_game_players_games foreign key (gpl_gms_id) references games (gms_id)
          );

create    table game_polls (
          gpo_gms_id integer,
          gpo_number integer,
          gpo_slack_message_id varchar(255),
          gpo_title varchar(255),
          gpo_status varchar(255),
          primary key (gpo_gms_id, gpo_number),
          constraint fk_game_polls_games foreign key (gpo_gms_id) references games (gms_id)
          );

create    table game_votes (
          gvo_gpo_gms_id integer,
          gvo_gpo_number integer,
          gvo_gpl_gms_id integer,
          gvo_gpl_slack_id varchar(255),
          gvo_voted_on_gpl_gms_id integer,
          gvo_voted_on_gpl_slack_id varchar(255),
          gvo_voted_at timestamp default current_timestamp,
          primary key (
          gvo_gpo_gms_id,
          gvo_gpo_number,
          gvo_gpl_gms_id,
          gvo_gpl_slack_id
          ),
          constraint fk_game_votes_polls foreign key (gvo_gpo_gms_id, gvo_gpo_number) references game_polls (gpo_gms_id, gpo_number),
          constraint fk_game_votes_players_from foreign key (gvo_gpl_gms_id, gvo_gpl_slack_id) references game_players (gpl_gms_id, gpl_slack_id),
          constraint fk_game_votes_players_to foreign key (
          gvo_voted_on_gpl_gms_id,
          gvo_voted_on_gpl_slack_id
          ) references game_players (gpl_gms_id, gpl_slack_id)
          );

create    table game_channels (
          gch_gms_id integer,
          gch_slack_id varchar(255),
          gch_name varchar(255),
          gch_type varchar(255),
          gch_archived boolean default false,
          gch_user_created varchar(255),
          gch_created_at timestamp default current_timestamp,
          primary key (gch_gms_id, gch_slack_id),
          constraint fk_game_channels_games foreign key (gch_gms_id) references games (gms_id)
          );

-- The following table is added for logging messages in the main channel(s)
create    table game_public_messages (
          gpm_gch_gms_id integer,
          gpm_gch_slack_id varchar(255),
          gpm_gpl_gms_id integer,
          gpm_gpl_slack_id varchar(255),
          gpm_slack_ts varchar(255),
          gpm_blocks text,
          gpm_files text,
          gpm_thread_ts varchar(255),
          gpm_created_at timestamp default current_timestamp,
          primary key (gpm_gch_slack_id, gpm_slack_ts),
          unique (gpm_slack_ts),
          constraint fk_game_public_messages_channels foreign key (gpm_gch_gms_id, gpm_gch_slack_id) references game_channels (gch_gms_id, gch_slack_id),
          constraint fk_game_public_messages_players foreign key (gpm_gpl_gms_id, gpm_gpl_slack_id) references game_players (gpl_gms_id, gpl_slack_id),
          constraint fk_game_public_messages_thread foreign key (gpm_thread_ts) references game_public_messages (gpm_slack_ts)
          );

create    index idx_game_public_messages_thread_ts on game_public_messages (gpm_thread_ts);

create    index idx_game_channels_game_archived_name on game_channels (gch_gms_id, gch_archived, gch_name);
